#!/usr/bin/with-contenv bash

echo "Starting Rclone."

if [ ! -d "${RCLONE_TARGET}" ]; then
  /bin/mkdir -p "${RCLONE_TARGET}"
  chown plex:plex "${RCLONE_TARGET}"
fi

IFS=' ' # space is set as delimiter
read -ra MOUNTS <<< ${RCLONE_MOUNT}

for i in "${!MOUNTS[@]}"; do # access each element of array
    if [ ! -d "${RCLONE_TARGET}/mount${i}" ]; then
      /bin/mkdir -p "${RCLONE_TARGET}/mount${i}"
      chown plex:plex "${RCLONE_TARGET}/mount${i}"
    fi
    /usr/sbin/rclone --config /config/rclone.conf mount ${MOUNTS[i]} ${RCLONE_TARGET}/mount${i} --allow-other ${RCLONE_ARGS}&
done
