#!/usr/bin/with-contenv bash

echo "Starting Rclone."

if [ ! -d "${RCLONE_TARGET}" ]; then
  /bin/mkdir -p "${RCLONE_TARGET}"
  chown plex:plex "${RCLONE_TARGET}"
fi

IFS=' ' # space is set as delimiter
read -ra MOUNTS <<< ${RCLONE_MOUNT}

for i in "${!MOUNTS[@]}"; do # access each element of array
    exec s6-setuidgid plex /bin/sh -c "/usr/sbin/rclone --config /config/rclone.conf mount ${MOUNTS[i]} ${RCLONE_TARGET}/mount${i} ${RCLONE_ARGS}"
done
